[package]
name = "vivo-downloader"
version = "0.1.0"
authors = ["fludixx <fludixs@protonmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.1"
urldecode = "0.1.1"
reqwest = "0.9.24"
indicatif = "0.13.0"
lust = "0.1.1"